### PR TITLE
Fix actor_factory and ego_vehicle

### PR DESCRIPTION
**Pull request by berndgassmann**
Fix: Actor factory uses correct actor transform also if no parent is set.
Feature: support an empty controller_launch command
Feature: Make waypoints publisher topic name configurable

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/526)

### CODE REVIEW

**Review by joel-mb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/526)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @berndgassmann, @fpasch, and @jackbart94)

___
*[carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py, line 153 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/526#-MYonjQ064FoueavZm3s:-MYonjQ064FoueavZm3t:bhi1eqt) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/b355e9416c6d11dc37445a4ec96f43b58c75f52d/carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py#L153)):*
> ```
>                 wheel_info.position.x = float(wheel_pos_in_ego_vehicle[0])
>                 wheel_info.position.y = float(-wheel_pos_in_ego_vehicle[1])
>                 wheel_info.position.z = float(wheel_pos_in_ego_vehicle[2])
> ```
Could you please update these changes. We just merged a PR fixing this issue (https://github.com/carla-simulator/ros-bridge/pull/527)

**Review by berndgassmann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/526)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @fpasch, @jackbart94, and @joel-mb)

___
*[carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py, line 153 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/526#-MYonjQ064FoueavZm3s:-MYoroq1A3aF-rOYsLL3:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/b355e9416c6d11dc37445a4ec96f43b58c75f52d/carla_ros_bridge/src/carla_ros_bridge/ego_vehicle.py#L153)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
>                 wheel_info.position.x = float(wheel_pos_in_ego_vehicle[0])
>                 wheel_info.position.y = float(-wheel_pos_in_ego_vehicle[1])
>                 wheel_info.position.z = float(wheel_pos_in_ego_vehicle[2])
> ```
Could you please update these changes. We just merged a PR fixing this issue (https://github.com/carla-simulator/ros-bridge/pull/527)
</blockquote></details>

Done.

**Review by joel-mb — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/526)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fpasch and @jackbart94)

**Review by fpasch — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/526)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @berndgassmann)

**Pull request merged**
