### PR TITLE
Add missing rosdep python3-opencv for ros-bridge

### PR DESCRIPTION
**Pull request by s-hillerk**
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/477)

### CODE REVIEW

**Review by fpasch — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/477)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @s-hillerk)

**Review by fpasch — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/477)* status: all files reviewed, 1 unresolved discussion (waiting on @s-hillerk)

___
*[carla_ros_bridge/package.xml, line 24 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/477#-MSgILxHBjqgH9enGQUX:-MSgILxHBjqgH9enGQUY:beexhll) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/eeaa40676fdbdbd7bd93022169d6db9466c8e68d/carla_ros_bridge/package.xml#L24)):*
> ```XML
>   <exec_depend>cv_bridge</exec_depend>
>   <exec_depend>python-transforms3d-pip</exec_depend>
>   <exec_depend>python3-opencv</exec_depend>
> ```

actually, that most likely breaks the support for ros melodic, because it's based on python 2.

**Comment by s-hillerk** [comment]
I can add a condition for ROS2. Is the missing dependency also breaking ROS1? Then a conditional `python-opencv` would be required as well.

**Comment by joel-mb** [comment]
Closing this PR as the ROS2 branch has been already merged with master.

**Pull request closed without merging**
