### PR TITLE
Semantic lidar + New communication pipeline

### PR DESCRIPTION
**Pull request by joel-mb**
This PR integrates the Semantic Lidar sensor and updates the communication pipeline.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/389)

### CODE REVIEW

**Comment by hofbi** [comment]
Could you add the new sensor to the [test_sensors.json](https://github.com/carla-simulator/ros-bridge/blob/master/carla_ros_bridge/test/test_sensors.json)

**Comment by hofbi** [comment]
@joel-mb Thanks for adding this. Could you also add a test for the semantic lidar. [This](https://github.com/carla-simulator/ros-bridge/blob/master/carla_ros_bridge/test/ros_bridge_client.py#L137) is the one for the regular lidar.

**Comment by joel-mb** [comment]
> @joel-mb Thanks for adding this. Could you also add a test for the semantic lidar. [This](https://github.com/carla-simulator/ros-bridge/blob/master/carla_ros_bridge/test/ros_bridge_client.py#L137) is the one for the regular lidar.

sure! thx!

**Review by hofbi — DISMISSED** [review]

**Review by fpasch — CHANGES_REQUESTED** [review]
> Reviewed 20 of 22 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/389)* status: 23 of 24 files reviewed, 1 unresolved discussion (waiting on @fpasch and @joel-mb)

___
*[carla_ros_bridge/src/carla_ros_bridge/lidar.py, line 100 at r4](https://reviewable.io/reviews/carla-simulator/ros-bridge/389#-MK9oKZ-E1MCHSvOTtb1:-MK9oKZ-E1MCHSvOTtb2:bts68wf) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/f806dac01a3365134960f54121d28441a058c10d/carla_ros_bridge/src/carla_ros_bridge/lidar.py#L100)):*
> ```
> lidar/semantic/
> ```
I would suggest to name it "semantic_lidar" or "lidar_semantic". Otherwise someone could believe that every lidar has a semantic aspect.

**Review by joel-mb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/389)* status: 21 of 24 files reviewed, 1 unresolved discussion (waiting on @fpasch and @joel-mb)

___
*[carla_ros_bridge/src/carla_ros_bridge/lidar.py, line 100 at r4](https://reviewable.io/reviews/carla-simulator/ros-bridge/389#-MK9oKZ-E1MCHSvOTtb1:-MKA2RML8erGKfkrRr86:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/f806dac01a3365134960f54121d28441a058c10d/carla_ros_bridge/src/carla_ros_bridge/lidar.py#L100)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

> ```
> lidar/semantic/
> ```
I would suggest to name it "semantic_lidar" or "lidar_semantic". Otherwise someone could believe that every lidar has a semantic aspect.
</blockquote></details>

Done.

**Review by fpasch — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/389)* status: 23 of 24 files reviewed, all discussions resolved (waiting on @joel-mb)

**Review by fpasch — APPROVED** [review]
> Reviewed 1 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/389)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
