### PR TITLE
DVS camera + New spawn sensor pipeline

### LINKED ISSUE #341: Support for DVS Camera missing
ROS Bridge should support DVS camera sensor data publishing.
https://carla.readthedocs.io/en/latest/ref_sensors/#dvs-camera

### PR DESCRIPTION
**Pull request by joel-mb**
This PR integrated the DVS camera sensor (https://carla.readthedocs.io/en/latest/ref_sensors/#dvs-camera).
It also updates the way the sensor configuration file is parsed to allow more flexible configurations.

Closes #341 #311

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/399)

### CODE REVIEW

**Review by fpasch — COMMENTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/399)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @fpasch and @joel-mb)

___
*[carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py, line 212 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/399#-MKF-Eqq6mGkE8gh243b:-MKF-Eqq6mGkE8gh243c:b30v6vy) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/f8ee9a64bae8efca94a346859c14b6cb5eb23178/carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py#L212)):*
> ```Python
>                 bp = bp_library.find(sensor_type)
>                 bp.set_attribute('role_name', sensor_id)
>                 for attribute, value in sensor_spec.items():
> ```

nice :+1: 
Why not also remove the special cases "width" and "height"?
___
*[carla_infrastructure/launch/carla_infrastructure.launch, line 6 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/399#-MKEydpf0VzG8-jeNvHZ:-MKEydpf0VzG8-jeNvH_:b-nga6rx) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/f8ee9a64bae8efca94a346859c14b6cb5eb23178/carla_infrastructure/launch/carla_infrastructure.launch#L6)):*
> ```XML
>   <arg name='port' default='2000'/>
>   <arg name='timeout' default='10'/>
>   <arg name="infrastructure_sensor_definition_file" default="$(find carla_infrastructure)/config/sensors.json"/>
> ```

that was intentionally left open to the user.
___
*[carla_infrastructure/src/carla_infrastructure/carla_infrastructure.py, line 93 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/399#-MKEyqjc7G9nIPoEwoPn:-MKEyqjc7G9nIPoEwoPo:b-dsdo29) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/f8ee9a64bae8efca94a346859c14b6cb5eb23178/carla_infrastructure/src/carla_infrastructure/carla_infrastructure.py#L93)):*
> ```Python
>                 bp = bp_library.find(sensor_type)
>                 bp.set_attribute('role_name', sensor_id)
>                 for attribute, value in sensor_spec.items():
> ```

nice :+1: 
why not also remove the special case?

**Review by joel-mb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/399)* status: 2 of 9 files reviewed, 3 unresolved discussions (waiting on @fpasch and @joel-mb)

___
*[carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py, line 212 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/399#-MKF-Eqq6mGkE8gh243b:-MK_Ldg374oVr5mZ6JjJ:b-b7plrq) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/f8ee9a64bae8efca94a346859c14b6cb5eb23178/carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py#L212)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

nice :+1: 
Why not also remove the special cases "width" and "height"?
</blockquote></details>

Done! I was maintaining these special cases to keep compatibility with the sensor configuration files (already updated)
___
*[carla_infrastructure/launch/carla_infrastructure.launch, line 6 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/399#-MKEydpf0VzG8-jeNvHZ:-MK_M6Jl4Veln1i5RnWJ:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/f8ee9a64bae8efca94a346859c14b6cb5eb23178/carla_infrastructure/launch/carla_infrastructure.launch#L6)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

that was intentionally left open to the user.
</blockquote></details>

Done.
___
*[carla_infrastructure/src/carla_infrastructure/carla_infrastructure.py, line 93 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/399#-MKEyqjc7G9nIPoEwoPn:-MK_M7HSCd6E7UcpKj10:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/f8ee9a64bae8efca94a346859c14b6cb5eb23178/carla_infrastructure/src/carla_infrastructure/carla_infrastructure.py#L93)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

nice :+1: 
why not also remove the special case?
</blockquote></details>

Done.

**Review by fpasch — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/399)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @fpasch and @joel-mb)

___
*[carla_ros_bridge/test/ros_bridge_client.py, line 147 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/399#-MK_QNv_BV08QB3QgSwA:-MK_QNv_BV08QB3QgSwB:b-6mqcp0) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/0380613c3e8faa5155794048a65c76a6a5eb2206/carla_ros_bridge/test/ros_bridge_client.py#L147)):*
> ```Python
>         self.assertEqual(msg.height, 600)
>         self.assertEqual(msg.width, 800)
> ```

one test missing, right? (for camera image)

**Review by fpasch — COMMENTED** [review]
Please also update README (we might have forgotten that for semantic lidar too)

> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/399#-:-MK_QeyC6J_-k_uRw5eX:b-38dus1)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @fpasch and @joel-mb)

**Review by fpasch — APPROVED** [review]
> Reviewed 1 of 9 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/399)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
