### PR TITLE
Format check

### PR DESCRIPTION
**Pull request by hofbi**
So far, all paths for the format and pylint were hardcoded in the check.sh and travis file. I tried to improve this by

* Replacing the check.sh with a Makefile
* Search for all files that should be format/pylint checked
* Add cmake_format package to ensure consistent cmake file format

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/293)

### CODE REVIEW

**Comment by hofbi** [comment]
Travis currently fails because of open pylint issues. I would suggest to disable the pylint check for this PR and fix them in another PR.

**Comment by hofbi** [comment]
@fpasch This one is also ready and passed.

**Comment by hofbi** [comment]
@fpasch Could you restart the CI build again. It should work as is.

**Comment by hofbi** [comment]
Great, it passed. Could you review the PR.

**Comment by hofbi** [comment]
@fpasch Anything that I need to change here?

**Comment by fpasch** [comment]
Thanks for the PR. Sorry for the delay.

**Pull request merged**
