### PR TITLE
Ros coordinates

### PR DESCRIPTION
**Pull request by joel-mb**
- Using ROS coordinate frame to define spawn points.
- New structure topic names.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/423)

### CODE REVIEW

**Review by fpasch — CHANGES_REQUESTED** [review]
> Reviewed 42 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/423)* status: all files reviewed, 11 unresolved discussions (waiting on @joel-mb)

___
*[carla_ad_agent/src/carla_ad_agent/basic_agent.py, line 50 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT2Bc1-rEsYyK2vWdz:-MNT2Bc23d9dQTPN1FyX:b-qqegw3) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ad_agent/src/carla_ad_agent/basic_agent.py#L50)):*
> ```Python
>             self._lights_id_list = []
>             self._actors_subscriber = rospy.Subscriber(
>                 "/carla/{}/actor_list".format(role_name), CarlaActorList,
> ```

the actor list is not within the role_name namespace, is it?
___
*[carla_ad_demo/config/carla_ad_demo.rviz, line 71 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT2vZo4gRxi98EH0MW:-MNT2vZo4gRxi98EH0MX:b1j97gd) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ad_demo/config/carla_ad_demo.rviz#L71)):*
> ```YAML
>       Enabled: true
>       Image Rendering: background and overlay
>       Image Topic: /carla/ego_vehicle/rgb_front/image
> ```

why did this change? the spectator_view is the camera that is moving with the rviz main window
___
*[carla_ad_demo/config/carla_ad_demo.rviz, line 78 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT33ib184SB4pb-cOX:-MNT33ib184SB4pb-cOY:bsndzaq) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ad_demo/config/carla_ad_demo.rviz#L78)):*
> ```YAML
>       Unreliable: false
>       Value: true
>       Visibility:
> ```

I added that because then you have a complete demo of all sensors. What's your plan there?
___
*[carla_ad_demo/config/sensors.json, line 1 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT2VIc1EvG0dhfVoW7:-MNT2VIc1EvG0dhfVoW8:b-84vy5s) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ad_demo/config/sensors.json#L1)):*
> ```JSON
> {
> ```

haven't we agreed to use a single sensors.json? Is it diverging now?
___
*[carla_ad_demo/launch/carla_ad_demo.launch, line 45 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT3E-D3tYu0vUXTYAu:-MNT3E-D3tYu0vUXTYAv:byr4ffv) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ad_demo/launch/carla_ad_demo.launch#L45)):*
> ```XML
>     <arg name='timeout' value='$(arg timeout)'/>
>     <arg name="vehicle_filter" value='$(arg vehicle_filter)'/>
>     <arg name="sensor_definition_file" default="$(find carla_ad_demo)/config/sensors.json"/>
> ```

see above
___
*[carla_ad_demo/launch/carla_ad_demo_with_scenario.launch, line 44 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT3Fcz6oorAiIC3EwK:-MNT3Fcz6oorAiIC3EwL:byr4ffv) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ad_demo/launch/carla_ad_demo_with_scenario.launch#L44)):*
> ```XML
>     <arg name='timeout' value='$(arg timeout)'/>
>     <arg name="vehicle_filter" value='$(arg vehicle_filter)'/>
>     <arg name="sensor_definition_file" default="$(find carla_ad_demo)/config/sensors.json"/>
> ```

see above
___
*[carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py, line 77 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT3T-G0gkBYBk6rFg3:-MNT3T-G0gkBYBk6rFg4:bxofbzk) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py#L77)):*
> ```Python
>             pose.position.x = float(spawn_point[0])
>             pose.position.y = float(spawn_point[1])
>             pose.position.z = float(spawn_point[2]) + 2
> ```

I would not add that implicitly here. Instead maybe add a comment in the launch file.
___
*[carla_infrastructure/config/sensors.json, line 57 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT4-p_4bvjob9d5AUP:-MNT4-p_4bvjob9d5AUQ:b1yiub0) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_infrastructure/config/sensors.json#L57)):*
> ```JSON
>             "rotation_frequency": 20
>         },
>         {
> ```

you're using these to spawn the "carla/...." sensors?
___
*[carla_ros_bridge/config/carla_default_rviz.cfg.rviz, line 144 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT4ZNQ4JWwWnr7pZ0i:-MNT4Rno3Krd_fkkiSKa:b36v6p4) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ros_bridge/config/carla_default_rviz.cfg.rviz#L144)):*
> ```YAML
>     - Class: rviz/MarkerArray
>       Enabled: true
>       Marker Topic: /carla/ego_vehicle/markers
> ```

hm. does it make sense to have that in the ego_vehicle namespace?
___
*[carla_ros_bridge/src/carla_ros_bridge/vehicle.py, line 40 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT5_j5CER6uJGT5TRg:-MNT5_j5CER6uJGT5TRh:bt6zvty) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ros_bridge/src/carla_ros_bridge/vehicle.py#L40)):*
> ```Python
>         :param carla_actor: carla vehicle actor object
>         :type carla_actor: carla.Vehicle
>         """
> ```

are you removing the "vehicle" namespace here?
___
*[carla_ros_bridge/src/carla_ros_bridge/walker.py, line 40 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT5mgt4LltcYsoLHJD:-MNT5mgt4LltcYsoLHJE:b-rindxg) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ros_bridge/src/carla_ros_bridge/walker.py#L40)):*
> ```Python
>         :param carla_actor: carla walker actor object
>         :type carla_actor: carla.Walker
>         """
> ```

are you removing the walker namespace here?

**Review by fpasch — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/423)* status: all files reviewed, 16 unresolved discussions (waiting on @joel-mb)

___
*[README.md, line 242 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNTEH03Ej0F2H52YGoU:-MNTEH046HY03RWiXGyK:b-3ogll9) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/334010a57a1dbec55185908234337fac2818777f/README.md#L242)):*
> ```Markdown
> 
> The tf data for the ego vehicle is published when this pseudo sensor is spawned.
> ```

isn't it the tf data for all actors?
___
*[README.md, line 252 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNTESM1C7DWsG5jkNH1:-MNTESM1C7DWsG5jkNH2:bm7l5pl) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/334010a57a1dbec55185908234337fac2818777f/README.md#L252)):*
> ```Markdown
> 
> ##### Speedometer Sensor
> ```

please mention unit here.
___
*[README.md, line 258 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNTEbaZ05XZZDyTg5T9:-MNTEbaZ05XZZDyTg5TA:buzifwi) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/334010a57a1dbec55185908234337fac2818777f/README.md#L258)):*
> ```Markdown
> 
> ##### Map Sensor
> ```

This sensor provides the OpenDRIVE map as a string on a latched topic.
___
*[README.md, line 264 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNTExdN5rYvqysxZySt:-MNTExdN5rYvqysxZySu:b-eqacwz) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/334010a57a1dbec55185908234337fac2818777f/README.md#L264)):*
> ```Markdown
> 
> ##### Object Sensor
> ```

Publishes all vehicles and walker. If attached to a parent, the parent is not contained.
___
*[README.md, line 353 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNTFRE45RJ71CLbfDi3:-MNTFRE45RJ71CLbfDi4:b-2a9c1f) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/334010a57a1dbec55185908234337fac2818777f/README.md#L353)):*
> ```Markdown
> | ------------------- | -------------------------------------------------------------- | ------------------------------------------------------ |
> | `/carla/status`     | [carla_msgs.CarlaStatus](https://github.com/carla-simulator/ros-carla-msgs/tree/master/msg/CarlaStatus.msg)       |                                                        |
> | `/carla/world_info` | [carla_msgs.CarlaWorldInfo](https://github.com/carla-simulator/ros-carla-msgs/tree/master/msg/CarlaWorldInfo.msg) | Info about the CARLA world/level (e.g. OPEN Drive map) |
> ```

Have you removed the walker_control_cmd?

**Review by joel-mb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/423)* status: 31 of 49 files reviewed, 16 unresolved discussions (waiting on @fpasch)

___
*[README.md, line 242 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNTEH03Ej0F2H52YGoU:-MNYimlGB1-sm7n-XLkX:b9ckpr0) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/334010a57a1dbec55185908234337fac2818777f/README.md#L242)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

isn't it the tf data for all actors?
</blockquote></details>

No. TF, odometry and speedometer pseudo sensors can only be used when attached to a vehicle right now.
___
*[README.md, line 252 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNTESM1C7DWsG5jkNH1:-MNYjMtEDdmGUGMvtm_c:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/334010a57a1dbec55185908234337fac2818777f/README.md#L252)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

please mention unit here.
</blockquote></details>

Done.
___
*[README.md, line 258 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNTEbaZ05XZZDyTg5T9:-MNYjNy18sCoYWcNZHsl:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/334010a57a1dbec55185908234337fac2818777f/README.md#L258)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

This sensor provides the OpenDRIVE map as a string on a latched topic.
</blockquote></details>

Done.
___
*[README.md, line 264 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNTExdN5rYvqysxZySt:-MNYjOfw2Zak-O_DYuHb:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/334010a57a1dbec55185908234337fac2818777f/README.md#L264)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

Publishes all vehicles and walker. If attached to a parent, the parent is not contained.
</blockquote></details>

Done.
___
*[README.md, line 353 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNTFRE45RJ71CLbfDi3:-MNYjQI_7lYY9rVBmpb0:b-azumh) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/334010a57a1dbec55185908234337fac2818777f/README.md#L353)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

Have you removed the walker_control_cmd?
</blockquote></details>

Added again. We will have to address this when the new spawn pipeline is available.
___
*[carla_ad_agent/src/carla_ad_agent/basic_agent.py, line 50 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT2Bc1-rEsYyK2vWdz:-MNYjXKQE6mAUETcL6ID:b3ymis0) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ad_agent/src/carla_ad_agent/basic_agent.py#L50)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

the actor list is not within the role_name namespace, is it?
</blockquote></details>

Done. I'm now using the carla_infrastructure package.
___
*[carla_ad_demo/config/carla_ad_demo.rviz, line 71 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT2vZo4gRxi98EH0MW:-MNYjxbG8girVH5nyq0U:b-886gsx) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ad_demo/config/carla_ad_demo.rviz#L71)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

why did this change? the spectator_view is the camera that is moving with the rviz main window
</blockquote></details>

Fixed
___
*[carla_ad_demo/config/carla_ad_demo.rviz, line 78 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT33ib184SB4pb-cOX:-MNYk0Os-C6x9pD_tVCV:bths4dz) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ad_demo/config/carla_ad_demo.rviz#L78)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

I added that because then you have a complete demo of all sensors. What's your plan there?
</blockquote></details>

Fixed. Using the generic sensor configuration file again.
___
*[carla_ad_demo/config/sensors.json, line 1 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT2VIc1EvG0dhfVoW7:-MNYk6KO18j6uK7K2VGS:b1slaw3) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ad_demo/config/sensors.json#L1)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

haven't we agreed to use a single sensors.json? Is it diverging now?
</blockquote></details>

Removed. Using the generic sensor configuration file again.
___
*[carla_ad_demo/launch/carla_ad_demo.launch, line 45 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT3E-D3tYu0vUXTYAu:-MNYkAMZ-awCm_0_1LRo:b1slaw3) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ad_demo/launch/carla_ad_demo.launch#L45)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

see above
</blockquote></details>

Removed. Using the generic sensor configuration file again.
___
*[carla_ad_demo/launch/carla_ad_demo_with_scenario.launch, line 44 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT3Fcz6oorAiIC3EwK:-MNYkFFU8IX682mWc36J:b1slaw3) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ad_demo/launch/carla_ad_demo_with_scenario.launch#L44)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

see above
</blockquote></details>

Removed. Using the generic sensor configuration file again.
___
*[carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py, line 77 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT3T-G0gkBYBk6rFg3:-MNYkHA91QSnHKSOq2WK:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ego_vehicle/src/carla_ego_vehicle/carla_ego_vehicle.py#L77)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

I would not add that implicitly here. Instead maybe add a comment in the launch file.
</blockquote></details>

Done.
___
*[carla_infrastructure/config/sensors.json, line 57 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT4-p_4bvjob9d5AUP:-MNYkId76eNURNjQobN4:bzd6zrr) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_infrastructure/config/sensors.json#L57)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

you're using these to spawn the "carla/...." sensors?
</blockquote></details>

Done. See above.
___
*[carla_ros_bridge/config/carla_default_rviz.cfg.rviz, line 144 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT4ZNQ4JWwWnr7pZ0i:-MNYkY2cEkSFDvjksEQw:bzd6zrr) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ros_bridge/config/carla_default_rviz.cfg.rviz#L144)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

hm. does it make sense to have that in the ego_vehicle namespace?
</blockquote></details>

Done. See above.
___
*[carla_ros_bridge/src/carla_ros_bridge/vehicle.py, line 40 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT5_j5CER6uJGT5TRg:-MNYkatb2wS6L9aZcbfS:b-ctat78) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ros_bridge/src/carla_ros_bridge/vehicle.py#L40)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

are you removing the "vehicle" namespace here?
</blockquote></details>

Yes. The vehicle namespace is not needed anymore. The namespace for each actor is now structured as follows: <PARENTs_ROLENAME>/<ACTOR_ROLENAME>.
___
*[carla_ros_bridge/src/carla_ros_bridge/walker.py, line 40 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNT5mgt4LltcYsoLHJD:-MNYkuWm8VQqj2QOLLvh:b-664lbs) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/361d22e63c4d9fb7918f4561d27061cc4dfa6114/carla_ros_bridge/src/carla_ros_bridge/walker.py#L40)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

are you removing the walker namespace here?
</blockquote></details>

Yes. See above. I'm leaving the control subscriber but this should be addressed in the future (probably with the new spawn pipeline).

**Review by fpasch — CHANGES_REQUESTED** [review]
> Reviewed 19 of 19 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/423)* status: all files reviewed, 3 unresolved discussions (waiting on @fpasch and @joel-mb)

___
*[carla_infrastructure/config/sensors.json, line 13 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNZibZ20k9gpLoM1I8l:-MNZibZ37epQ5aobwsl5:b3up15x) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/e117a3ecff3af198177affbd2c7594a371c23cd9/carla_infrastructure/config/sensors.json#L13)):*
> ```JSON
>         {
>             "type": "sensor.pseudo.markers",
>             "id": "markers"
> ```

what's the reason to remove "/carla/objects"?

**Review by joel-mb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/423)* status: 48 of 49 files reviewed, 3 unresolved discussions (waiting on @fpasch)

___
*[carla_infrastructure/config/sensors.json, line 13 at r3](https://reviewable.io/reviews/carla-simulator/ros-bridge/423#-MNZibZ20k9gpLoM1I8l:-MNZk5s87uP6uMCjs1tl:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/e117a3ecff3af198177affbd2c7594a371c23cd9/carla_infrastructure/config/sensors.json#L13)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

what's the reason to remove "/carla/objects"?
</blockquote></details>

Done.

**Review by fpasch — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/423)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @joel-mb)

**Pull request merged**
