### PR TITLE
Fix rgb camera attributes

### PR DESCRIPTION
**Pull request by fpasch**
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/340)

### CODE REVIEW

**Comment by fpasch** [comment]
As specified in https://github.com/carla-simulator/carla/pull/3115

**Comment by marcgpuig** [comment]
@joel-mb @fpasch
We've just changed the `exposure_compensation` value from `0.0` to `-2.2`.
Just curious, why these values are provided in this file? You can access these default values from the API itself. Is it just a helper for the user so they know which parameters are available?

**Comment by fpasch** [comment]
@marcgpuig Yes. It should support users to easily adapt their sensor setup.

**Comment by fpasch** [comment]
Now works with latest CARLA master.(after merging carla-simulator/carla#3115)

**Pull request merged**
