### PR TITLE
new carla_ad_agent structure and tuned longitudinal controller

### PR DESCRIPTION
**Pull request by jbmag**
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/470)

### CODE REVIEW

**Review by fpasch — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/470)* status: all files reviewed, 7 unresolved discussions (waiting on @jbmag)

___
*[carla_ad_agent/CMakeLists.txt, line 24 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/470#-MUI8PQ71JLutZWab-Yv:-MUI8PQ71JLutZWab-Yw:bdc4pgo) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/2b338c6f65a1b1d5e9b449b681f63dcffa411c0a/carla_ad_agent/CMakeLists.txt#L24)):*
> ```CMake
>                    src/carla_ad_agent/local_planner.py
>           DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
>   message(${CATKIN_PACKAGE_BIN_DESTINATION})
> ```

left over
___
*[carla_ad_agent/launch/carla_ad_agent.launch.py, line 22 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/470#-MUI8irhA1EcPrJ8kmYh:-MUI8irhA1EcPrJ8kmYi:b-rbr466) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/2b338c6f65a1b1d5e9b449b681f63dcffa411c0a/carla_ad_agent/launch/carla_ad_agent.launch.py#L22)):*
> ```Python
>             default_value='True'
>         ),
>         launch.actions.DeclareLaunchArgument(
> ```

not used anywhere.
___
*[carla_ad_agent/src/carla_ad_agent/local_planner.py, line 101 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/470#-MUI9J40BNwi12GDYrCY:-MUI9J40BNwi12GDYrCZ:bdc4pgo) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/2b338c6f65a1b1d5e9b449b681f63dcffa411c0a/carla_ad_agent/src/carla_ad_agent/local_planner.py#L101)):*
> ```Python
>                 rclpy.spin_once(self, timeout_sec=0)
> 
>         # self.f = open('data.txt', 'w')
> ```

left over
___
*[carla_ad_agent/src/carla_ad_agent/local_planner.py, line 172 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/470#-MUI9DWQ0kjrbWPJAgSp:-MUI9DWQ0kjrbWPJAgSq:bdc4pgo) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/2b338c6f65a1b1d5e9b449b681f63dcffa411c0a/carla_ad_agent/src/carla_ad_agent/local_planner.py#L172)):*
> ```Python
>             self._target_speed, self._current_speed, self._current_pose, self.target_route_point)
> 
>         # self.f.write('{}, {}, {}, {}, {}, \n'.format(self.get_time(), self._target_speed, self._current_speed, control.throttle, self._vehicle_controller._lat_controller.error))
> ```

left over
___
*[carla_ad_agent/src/carla_ad_agent/local_planner.py, line 227 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/470#-MUI9M7h-j1cXJ2I1K-3:-MUI9M7h-j1cXJ2I1K-4:bdc4pgo) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/2b338c6f65a1b1d5e9b449b681f63dcffa411c0a/carla_ad_agent/src/carla_ad_agent/local_planner.py#L227)):*
> ```Python
>             else:
>                 update_timer.destroy()
>         # local_planner.f.close()
> ```

left over
___
*[carla_ad_demo/launch/carla_ad_demo.launch.py, line 9 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/470#-MUI9Uv_DwbGNUcLuFI0:-MUI9Uv_DwbGNUcLuFI1:bonxz95) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/2b338c6f65a1b1d5e9b449b681f63dcffa411c0a/carla_ad_demo/launch/carla_ad_demo.launch.py#L9)):*
> ```Python
> 
> 
> def launch_carla_spawn_object(context, *args, **kwargs):  # TODO find better solution
> ```

haven't you found an easier solution for that?
___
*[carla_ad_demo/launch/carla_ad_demo.launch.py, line 89 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/470#-MUI9g8J7Z6qOjgAF1UV:-MUI9g8J7Z6qOjgAF1UW:btj9kl0) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/2b338c6f65a1b1d5e9b449b681f63dcffa411c0a/carla_ad_demo/launch/carla_ad_demo.launch.py#L89)):*
> ```
> # only synchronous mode is supported
> ```
please add: # only synchronous mode is supported

**Review by jbmag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/470)* status: 16 of 21 files reviewed, 7 unresolved discussions (waiting on @fpasch)

___
*[carla_ad_agent/CMakeLists.txt, line 24 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/470#-MUI8PQ71JLutZWab-Yv:-MUIIxdM5f7m7Y0iOmeB:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/2b338c6f65a1b1d5e9b449b681f63dcffa411c0a/carla_ad_agent/CMakeLists.txt#L24)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

left over
</blockquote></details>

Done.
___
*[carla_ad_agent/launch/carla_ad_agent.launch.py, line 22 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/470#-MUI8irhA1EcPrJ8kmYh:-MUIIzSfCFMmAU6GpuN6:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/2b338c6f65a1b1d5e9b449b681f63dcffa411c0a/carla_ad_agent/launch/carla_ad_agent.launch.py#L22)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

not used anywhere.
</blockquote></details>

Done.
___
*[carla_ad_agent/src/carla_ad_agent/local_planner.py, line 101 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/470#-MUI9J40BNwi12GDYrCY:-MUIJ-ThC3s0gIu3fozd:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/2b338c6f65a1b1d5e9b449b681f63dcffa411c0a/carla_ad_agent/src/carla_ad_agent/local_planner.py#L101)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

left over
</blockquote></details>

Done.
___
*[carla_ad_agent/src/carla_ad_agent/local_planner.py, line 172 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/470#-MUI9DWQ0kjrbWPJAgSp:-MUIJ0yl8y4VNWHsWBwp:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/2b338c6f65a1b1d5e9b449b681f63dcffa411c0a/carla_ad_agent/src/carla_ad_agent/local_planner.py#L172)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

left over
</blockquote></details>

Done.
___
*[carla_ad_agent/src/carla_ad_agent/local_planner.py, line 227 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/470#-MUI9M7h-j1cXJ2I1K-3:-MUIJ2Zz71Kmu0InAuR4:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/2b338c6f65a1b1d5e9b449b681f63dcffa411c0a/carla_ad_agent/src/carla_ad_agent/local_planner.py#L227)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

left over
</blockquote></details>

Done.
___
*[carla_ad_demo/launch/carla_ad_demo.launch.py, line 9 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/470#-MUI9Uv_DwbGNUcLuFI0:-MUIJ3nHDvT_XMIg5HU6:bz4wfjs) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/2b338c6f65a1b1d5e9b449b681f63dcffa411c0a/carla_ad_demo/launch/carla_ad_demo.launch.py#L9)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

haven't you found an easier solution for that?
</blockquote></details>

No not for that case. The parameter name depends on another parameter, and I can't find another way to use a substitution there.
___
*[carla_ad_demo/launch/carla_ad_demo.launch.py, line 89 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/470#-MUI9g8J7Z6qOjgAF1UV:-MUIJLv48pIxzvN6SZDQ:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/2b338c6f65a1b1d5e9b449b681f63dcffa411c0a/carla_ad_demo/launch/carla_ad_demo.launch.py#L89)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

> ```
> # only synchronous mode is supported
> ```
please add: # only synchronous mode is supported
</blockquote></details>

Done.

**Review by fpasch — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/470)* status: all files reviewed, 1 unresolved discussion (waiting on @jbmag)

___
*[carla_ad_demo/launch/carla_ad_demo.launch.py, line 9 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/470#-MUI9Uv_DwbGNUcLuFI0:-MUIKNM_5SKG6d0_jJwb:bq0h8ml) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/2b338c6f65a1b1d5e9b449b681f63dcffa411c0a/carla_ad_demo/launch/carla_ad_demo.launch.py#L9)):*
<details><summary><i>Previously, jbmag (Jean-Baptiste Magnin) wrote…</i></summary><blockquote>

No not for that case. The parameter name depends on another parameter, and I can't find another way to use a substitution there.
</blockquote></details>

ok. could you please remove my "#TODO find better solution"?

**Review by jbmag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/470)* status: 19 of 21 files reviewed, 1 unresolved discussion (waiting on @fpasch)

___
*[carla_ad_demo/launch/carla_ad_demo.launch.py, line 9 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/470#-MUI9Uv_DwbGNUcLuFI0:-MUIPoqR2BiDFslMEFbw:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/2b338c6f65a1b1d5e9b449b681f63dcffa411c0a/carla_ad_demo/launch/carla_ad_demo.launch.py#L9)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

ok. could you please remove my "#TODO find better solution"?
</blockquote></details>

Done.

**Review by fpasch — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/470)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jbmag)

**Pull request merged**
