### PR TITLE
Debian package

### PR DESCRIPTION
**Pull request by hofbi**
* Build debian package on every
* Refactor debian creation script

In another PR I will prepare storing the debian package as artifacts. With this we will get a kind of nightly build. Further I will prepare the deployment to the carla ppa

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/418)

### CODE REVIEW

**Comment by hofbi** [comment]
Depends on #421

**Review by joel-mb — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/418)* status: all files reviewed, 1 unresolved discussion (waiting on @hofbi)

___
*[.gitignore, line 11 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/418#-MNZnPus-1LLdxXLFWeA:-MNZnPus-1LLdxXLFWeB:b-g2lt0f) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/6bd4206056d0971a195d1789040ce23e0bd68d5c/.gitignore#L11)):*
> ```ignore
> 
> # Packaging
> carla-ros-debian
> ```

This is no longer necessary?

**Comment by hofbi** [comment]
Right. This was an artifact from the previous version. I removed it.

**Review by joel-mb — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/418)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
