### PR TITLE
Sensor TFs with respect to vehicle in sync mode

### PR DESCRIPTION
**Pull request by joel-mb**
Sensor TFs are now published wrt the vehicle frame in synchronous mode.
Regular tfs have been used instead of static tfs as intermittent transform may be needed depending on the use case (e.g., stopping/regenerating the ego vehicle).

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/430)

### CODE REVIEW

**Review by fpasch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/430)* status: 0 of 29 files reviewed, 2 unresolved discussions (waiting on @joel-mb)

___
*[carla_ros_bridge/src/carla_ros_bridge/pseudo_actor.py, line 23 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/430#-MO0iFYa5tSKRidDeYR2:-MO0iFYa5tSKRidDeYR3:bpznurp) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/cebd76a0d91ae0f810b78bf9eb9b9e13f4c3fd9b/carla_ros_bridge/src/carla_ros_bridge/pseudo_actor.py#L23)):*
> ```
> spawn_pose
> ```
we only need a `relative_spawn_pose`, right? So why not setting it to `None` as default. Also maybe add that this is only relevant if parent is set.
___
*[carla_ros_bridge/src/carla_ros_bridge/pseudo_actor.py, line 41 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/430#-MO0hoeh-NPEbAk37LUO:-MO0hoeiBMeDsc1Pe98V:b-d45ahf) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/cebd76a0d91ae0f810b78bf9eb9b9e13f4c3fd9b/carla_ros_bridge/src/carla_ros_bridge/pseudo_actor.py#L41)):*
> ```Python
>         self.name = name
>         self.parent = parent
>         self.spawn_pose = spawn_pose
> ```

pseudo actors will never have a relative spawn position, right? So why not moving it to Actor or better Sensor?

**Review by joel-mb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/430)* status: 0 of 18 files reviewed, 2 unresolved discussions (waiting on @fpasch)

___
*[carla_ros_bridge/src/carla_ros_bridge/pseudo_actor.py, line 23 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/430#-MO0iFYa5tSKRidDeYR2:-MOC3FU3EChJENFdfx4R:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/cebd76a0d91ae0f810b78bf9eb9b9e13f4c3fd9b/carla_ros_bridge/src/carla_ros_bridge/pseudo_actor.py#L23)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

> ```
> spawn_pose
> ```
we only need a `relative_spawn_pose`, right? So why not setting it to `None` as default. Also maybe add that this is only relevant if parent is set.
</blockquote></details>

Done.
___
*[carla_ros_bridge/src/carla_ros_bridge/pseudo_actor.py, line 41 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/430#-MO0hoeh-NPEbAk37LUO:-MOC3HTK34Cmb1qXTKp_:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/cebd76a0d91ae0f810b78bf9eb9b9e13f4c3fd9b/carla_ros_bridge/src/carla_ros_bridge/pseudo_actor.py#L41)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

pseudo actors will never have a relative spawn position, right? So why not moving it to Actor or better Sensor?
</blockquote></details>

Done.

**Review by fpasch — CHANGES_REQUESTED** [review]
> Reviewed 19 of 29 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/430)* status: all files reviewed, 1 unresolved discussion (waiting on @joel-mb)

___
*[carla_ros_bridge/src/carla_ros_bridge/sensor.py, line 174 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/430#-MOC4AK6BoBH2mNx7tfb:-MOC4AK6BoBH2mNx7tfc:b-2yy4th) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/517c1a500599d8eee53ce9a7228e391a3b445761/carla_ros_bridge/src/carla_ros_bridge/sensor.py#L174)):*
> ```Python
>                 rospy.logdebug("{}({}): process {}".format(
>                     self.__class__.__name__, self.get_id(), frame))
>                 #self.publish_tf(trans.carla_transform_to_ros_pose(carla_sensor_data.transform))
> ```

required?

**Review by joel-mb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/430)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @fpasch)

___
*[carla_ros_bridge/src/carla_ros_bridge/sensor.py, line 174 at r2](https://reviewable.io/reviews/carla-simulator/ros-bridge/430#-MOC4AK6BoBH2mNx7tfb:-MOCBC6b3qiWqHf21upM:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/517c1a500599d8eee53ce9a7228e391a3b445761/carla_ros_bridge/src/carla_ros_bridge/sensor.py#L174)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

required?
</blockquote></details>

Done.

**Review by fpasch — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/430)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @joel-mb)

**Pull request merged**
