### PR TITLE
Adds a ring field in lidar point_cloud_msg

### PR DESCRIPTION
**Pull request by KevinLADLee**
Refers:  #431 #416

Add ring field in published pointcloud using get_point_count() in carla.LidarMeasurement

[carla.LidarMeasurement](https://carla.readthedocs.io/en/latest/python_api/#carlalidarmeasurement)

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/432)

### CODE REVIEW

**Comment by KevinLADLee** [comment]
Screenshot from 2020-12-09 16-59-21

Test in 0.9.10.1.

**Comment by Opletts** [comment]
The `ring` values produced by this don't match the `ring` values of #431. The `ring` array is reversed in this PR.
I've validated the values produced by #431 against a real lidar pointcloud which produces the `ring` field and the values match.

Ideally, we'd just use `get_point_count()` and reverse the array after the stacking.
But there might be a hidden serialization issue in `carla.LidarMeasurement`, or maybe I just don't understand it properly. If someone could have a look and confirm?

**Comment by KevinLADLee** [comment]
Screenshot from 2020-12-10 11-04-24
Hello @Opletts. Thanks for your review. I also notice that the `ring` array is reversed to your pr #431. This picture is my Hesai Pandar64 visualization result, and I think the `ring` array sequence in the picture is the same as this pr. Maybe the lidar channel definition is different between your lidar and mine? Could you please tell me which lidar you use?

Also, what's your meaning for ' the hidden serialization issue ' in `carla.LidarMeasurement`? In my opinion, I think this change only affects users of ros-bridge, and has nothing to do with the serialization in LibCarla. I only changed the message advertised by the lidar_publisher.

**Comment by Opletts** [comment]
I was using a Velodyne Puck VLP-16 for my validation. If you could use your lidar and the method in #431 to confirm if it is indeed a channel definition problem by adding `np.count_nonzero(produced_ring != actual_ring)` or something.

> Also, what's your meaning for ' the hidden serialization issue ' in carla.LidarMeasurement? In my opinion, I think this change only affects users of ros-bridge, and has nothing to do with the serialization in LibCarla.

I thought maybe the binary data is reversed or maybe `get_point_count()` returns values from the end of the pointcloud array.

**Comment by KevinLADLee** [comment]
> I was using a Velodyne Puck VLP-16 for my validation. If you could use your lidar and the method in #431 to confirm if it is indeed a channel definition problem by adding `np.count_nonzero(produced_ring != actual_ring)` or something.
> 
> > Also, what's your meaning for ' the hidden serialization issue ' in carla.LidarMeasurement? In my opinion, I think this change only affects users of ros-bridge, and has nothing to do with the serialization in LibCarla.
> 
> I thought maybe the binary data is reversed or maybe `get_point_count()` returns values from the end of the pointcloud array.

Screenshot from 2020-12-10 17-28-47
Screenshot from 2020-12-10 17-27-14

I think the sequences of channels are different between different lidar manufacturer. So I think it’s better to forward directly according to the channel definition in LibCarla.

**Pull request closed without merging**
