### PR TITLE
Adds a ring field to the published pointcloud

### LINKED ISSUE #416: Generating ring and time fields for lidars
Velodyne lidars publish `PointCloud2` messages with the `fields` array containing :
- `x` , type : `float32`
- `y` , type : `float32`
- `z` , type : `float32`
- `intensity` , type : `float32`
- `ring` , type : `uint16`
- `time` , type : `float32`

`ring` : Tells us which channel of the lidar the point belongs to.
`time` : Tells us the relative time at which the point was received during one rotation. If the `rotation_frequency` is **10Hz**, values would vary between **0-0.1s**)

Carla only publishes `XYZI` points, not `XYZIRT`. I think adding these two fields would be quite useful. I've made changes locally to generate `ring` in [lidar.py](https://github.com/carla-simulator/ros-bridge/blob/master/carla_ros_bridge/src/carla_ros_bridge/lidar.py#L53) and can open a PR for review.

Generating the `time` field on the other hand is quite difficult. We've already received the binary data in [lidar.py](https://github.com/carla-simulator/ros-bridge/blob/master/carla_ros_bridge/src/carla_ros_bridge/lidar.py#L53) so it's impossible to get that field here. I'm guessing changes to the lidar api in Carla would be required to make this possible. Any suggestions?

### PR DESCRIPTION
**Pull request by Opletts**
Fixes #416
Each `PointCloud2` message has an additional `ring` field.
Published points are in the format of **XYZIR**.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/431)

### CODE REVIEW

**Review by fpasch — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/431)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Opletts)

___
*[carla_ros_bridge/src/carla_ros_bridge/lidar.py, line 74 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/431#-MQGSUpn3yUL_eworxZQ:-MQGSUpn3yUL_eworxZR:b-vk4w7x) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/e7cbcc65bc345a7c8267837789240ce586a30d9b/carla_ros_bridge/src/carla_ros_bridge/lidar.py#L74)):*
> ```
>         channels = float(self.carla_actor.attributes.get('channels'))
>         lower_fov = float(self.carla_actor.attributes.get('lower_fov'))
>         upper_fov = float(self.carla_actor.attributes.get('upper_fov'))
> ```
please move "static" calculations into __init__
___
*[carla_ros_bridge/src/carla_ros_bridge/lidar.py, line 81 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/431#-MQGSlbQ0vmezTVr7XPu:-MQGSlbQ0vmezTVr7XPv:b-lgqy2c) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/e7cbcc65bc345a7c8267837789240ce586a30d9b/carla_ros_bridge/src/carla_ros_bridge/lidar.py#L81)):*
> ```
>         fov_down = lower_fov / 180.0 * numpy.pi
>         fov = (abs(lower_fov) + abs(upper_fov)) / 180.0 * numpy.pi
> ```
same here

**Comment by Opletts** [comment]
I've made additional changes according to #432 since it's closed now. It's a much cleaner way to implement this as you can just use `get_point_count()`.

**Review by Opletts — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/431)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @fpasch)

___
*[carla_ros_bridge/src/carla_ros_bridge/lidar.py, line 74 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/431#-MQGSUpn3yUL_eworxZQ:-MTZhyP06g-lPi40qrDz:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/e7cbcc65bc345a7c8267837789240ce586a30d9b/carla_ros_bridge/src/carla_ros_bridge/lidar.py#L74)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

> ```
>         channels = float(self.carla_actor.attributes.get('channels'))
>         lower_fov = float(self.carla_actor.attributes.get('lower_fov'))
>         upper_fov = float(self.carla_actor.attributes.get('upper_fov'))
> ```
please move "static" calculations into __init__
</blockquote></details>

Done.
___
*[carla_ros_bridge/src/carla_ros_bridge/lidar.py, line 81 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/431#-MQGSlbQ0vmezTVr7XPu:-MTZhq4K3r4u_18L9N2u:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/e7cbcc65bc345a7c8267837789240ce586a30d9b/carla_ros_bridge/src/carla_ros_bridge/lidar.py#L81)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

> ```
>         fov_down = lower_fov / 180.0 * numpy.pi
>         fov = (abs(lower_fov) + abs(upper_fov)) / 180.0 * numpy.pi
> ```
same here
</blockquote></details>

Done.

**Review by joel-mb — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/431)* status: all files reviewed, 2 unresolved discussions (waiting on @fpasch)

**Comment by joel-mb** [comment]
Hi! I've run a benchmark and it seems that this can be time-consuming for some configurations (when using more than one lidar). I see two options to solve this:

(1) Introduce the ring attribute directly into the raw data (this needs to be done directly in CARLA) to avoid stacking the arrays.
(2) Make this new field optional by introducing a new pseudo-attribute.

I'll start talking with the CARLA core team to see if option (1) is feasible. Also, I will start working on option (2). Either way, this will happen after the ros2 branch becomes the new master.

**Comment by Opletts** [comment]
Makes sense, I was a little worried about it being time consuming but it works well enough for a single lidar so I didn't bother.

> (1) Introduce the ring attribute directly into the raw data (this needs to be done directly in CARLA) to avoid stacking the arrays.

This would be ideal, right? And if they do decide to introduce the `ring` attribute as part of the raw data, could they also add the `time` attribute alongside it as mentioned in #416?

> (2) Make this new field optional by introducing a new pseudo-attribute.

This is a a good enough workaround, and if you're working on it, should I close this PR and leave the issue open?

**Comment by joel-mb** [comment]
> This would be ideal, right? And if they do decide to introduce the `ring` attribute as part of the raw data, could they also add the `time` attribute alongside it as mentioned in #416?
yeah, this would be ideal. I will report the addition of this new field as well. I'll let you know what's the final decision.

> This is a a good enough workaround, and if you're working on it, should I close this PR and leave the issue open?
yes. please close this PR. I'll update all the progress about this feature there.

thanks!

**Comment by hey2016** [comment]
> `time` attribute

Hi，Opletts，have you add time attribute to the pointcloud already  @Opletts

**Comment by Robotics010** [comment]
Hi @joel-mb ! Is there any news about adding ring field to carla lidar measurement? Could you refer to the opened issue in carla repo to track its progress?

**Pull request closed without merging**
