### PR TITLE
Include submodules in clone instructions for ROS 1

### LINKED ISSUE #512: docker git submodule
Before using the `./docker/build.sh` the git submodule needs to be activated with `git submodule update --init`.

I added the following to my build.sh in line 16:

```shell
cd ${SCRIPT_DIR}/..
git submodule update --init
cd ${SCRIPT_DIR}
```
but I don't think that this is the best way, therefore I haven't created a pull request.

### PR DESCRIPTION
**Pull request by hofbi**
It is already included in the ROS 2 readme so we should also have this for ROS 1

Closes #512

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/513)

### CODE REVIEW

**Review by joel-mb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/513)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @hofbi)

___
*[README.ros.md, line 35 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/513#-MWi1j6e-n_1aACdmCP3:-MWi1j6e-n_1aACdmCP4:b-fgc1p9) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/27a75cca4610e821e9fd167644fdd0de8889d800/README.ros.md#L35)):*
> ```
>     cd ros-bridge
>     git submodule update --init
> ```
Please remove these lines, as we are already cloning the submodue with the `--recurse-submodules` argument.
___
*[README.ros.md, line 36 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/513#-MWi2-s2CbPyBcN6SAwn:-MWi2-s2CbPyBcN6SAwo:bf8z1bf) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/27a75cca4610e821e9fd167644fdd0de8889d800/README.ros.md#L36)):*
> ```
> cd ../catkin_ws/src
> ```
I think this also needs to be adapted if the previous lines are removed.

**Comment by hofbi** [comment]
I updated the readme and tried to make it similar to the ROS2 instructions

**Review by joel-mb — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/513)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @hofbi)

**Review by joel-mb — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/513)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hofbi)

**Pull request merged**
