### PR TITLE
Supporting ros noetic

### PR DESCRIPTION
**Pull request by hofbi**
This contains some first contributions for supporting ros noetic. Current status

* Missing packages
  * [x] derived-object_msgs -> WIP https://github.com/astuff/astuff_sensor_msgs/issues/55
  * [x] python-catkin-tools -> WIP https://github.com/catkin/catkin_tools/issues/594
* Carla python API for python 3.8
  * Ideally install over PiPy
  * Currently the build for python 3.8 fails -> open PR in https://github.com/carla-simulator/carla/pull/2857

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/323)

### CODE REVIEW

**Comment by fpasch** [comment]
@hofbi A switch to colcon would solve the issue with python-catkin-tools, right?

**Comment by hofbi** [comment]
I am currently waiting for the python3-catkin-tools as mentioned in the task list above. So far, I did not plan to integrate the ros2 colcon build. Not sure that I understood your question.

**Comment by fpasch** [comment]
colcon is also supporting ros1. Please give it a try:
```
    sudo apt install python3-colcon-common-extensions
    source /opt/ros/melodic/setup.bash
    colcon build

**Comment by hofbi** [comment]
@fpasch The colcon build fails only for the scenario runner

```shell
--- stderr: carla_ros_scenario_runner                                             
  File "opt/carla-ros-bridge/install/carla_ros_scenario_runner/lib/python3/dist-packages/carla_ros_scenario_runner/carla_ros_scenario_runner.py", line 31
    print "ERROR: CARLA Python Egg not available. Please add \
        <CARLA_DIR>/PythonAPI/carla/dist/carla-<CARLA_VERSION>-\
        py<PYTHON_VERSION>-linux-x86_64.egg to your PYTHONPATH."
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("ERROR: CARLA Python Egg not available. Please add \
        <CARLA_DIR>/PythonAPI/carla/dist/carla-<CARLA_VERSION>-\
        py<PYTHON_VERSION>-linux-x86_64.egg to your PYTHONPATH.")?

---
```

But the python path is defined properly as I am able to import carla correctly.

**Comment by tlobig** [comment]
Got Ubuntu 20.04 here with Noetic. Carla built with some adjustments I adapted from https://github.com/carla-simulator/carla/pull/2787

got catkin tools using:
sudo apt-get install python3-catkin-tools

I was able to build just fine with "catkin build" - only had to update CMakeLists.txt in pcl_recorder to use compile option c++17 instead of c++11 because some of the dependent libs don't work with just c++11 - maybe c++14 would be fine, too.

However I then get other issues with my environment when trying to roslaunch the example (i.e. "no module pkg_resources")
so maybe I need to make similar changes as the above pull request for Carla.

notice: I'm only just starting out, so I might easily miss important steps

**Comment by tlobig** [comment]
ok, python2 was in the mix, fixed it by
sudo apt install python-is-python3

then pygame was missing - missing depency which should be installed in the rosdep step?

it then launches, but I get constant
  File "/home/fascar/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/sensor.py", line 105, in _callback_sensor_data
    self.sensor_data_updated(carla_sensor_data)
  File "/home/fascar/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/lidar.py", line 59, in sensor_data_updated
    lidar_data = numpy.fromstring(
TypeError: fromstring() argument 1 must be read-only bytes-like object, not memoryview

smells very much like a python2 vs. python3 thing

**Comment by hofbi** [comment]
@fpasch Any idea how to solve the code review error. I don't see for which package we need to fix the version. From my side this PR is ready.

**Review by fpasch — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/323)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
