### PR TITLE
[ROS2] Port carla_ackermann_control

### PR DESCRIPTION
**Pull request by s-hillerk**
This PR ports the `carla_ackermann_control` package to ROS2. I tried to have pretty commits for easy review :smiley:

Notable changes:
- As pure ament python packages do not yet support message generation, create a new packge `carla_ackermann_msgs` and move all messages over.
- Dynamic parameter reconfiguration is a default feature in ROS2 now, so the two versions have different code paths for it.
- The launch file does no longer start nodes in different namespaces depending on the `role_name`. This was done to be able to keep using the `settings.yaml` for loading configurations.
- `ros_compatible_node` got new helper functions.
- The colcon skip-mixin allows building of `carla_ackermann_control` now.

I did not test the changes in ROS1, but made all adjustments in a best-effort manner to have it still supported.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/377)

### CODE REVIEW

**Comment by fpasch** [comment]
resolves #273

**Comment by s-hillerk** [comment]
Considering #380 together with this PR might save some time.

It might be helpful to have a good idea of
- what are global and node-local settings
- where to define them
- how they take precedence
- how to reconfigure them at runtime
- ROS1/2 differences regarding parameters (global namespace vs. node-local params)

Also, having the `/carla` namespace hard-coded in the node looks like a code smell to me.

**Comment by fpasch** [comment]
@s-hillerk  To keep things simple, we plan to completely switch to private parameters, even for ROS1. You might have seen it [here](https://github.com/carla-simulator/ros-bridge/blob/ros2/ros_compatibility/src/ros_compatibility/ros_compatible_node.py#L62).

You seem to be familiar with this topic. Do you think this approach makes sense?

**Comment by jbmag** [comment]
Hi @s-hillerk , there were a few things that prevented your ackermann2 branch to run with ROS1, so I fixed that. 
Also, we're trying to make it work for eloquent first (not foxy), and the function _add_on_set_parameters_callback_ is not available there, so I switched it to the old one (_set_parameters_callback_), it should be enough in this particular case, while also still working with foxy.
Finally, I fixed the few conflicts with the latest ros2 branch, in particular in _ros_compatibility_ your function _now_sec()_ had already been added as _get_time()_ in parallel to this PR.

**Review by fpasch — APPROVED** [review]
> Reviewed 13 of 20 files at r1, 4 of 5 files at r2, 2 of 2 files at r3, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/377)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by s-hillerk** [comment]
@fpasch I think this is a nice approach that makes keeping compatibility easier.

@jbmag Thank you very much for testing this out and implementing the required changes!

**Pull request merged**
