### PR TITLE
Scenario runner ros2

### PR DESCRIPTION
**Pull request by jbmag**
Port of ros_scenario_runner to ROS2!
Some things to be noted:

- I used the application_runner class to launch the controller in ROS2, it's not running directly the launchfile through ROS2's LaunchService
- I renamed carla_ros_scenario_runner.py to carla_ros_scenario_runner_node.py, to avoid an import problem in ROS2
- I had to modifiy some camera parameters in _carla_ego_vehicle/config/sensors.json_, to use carla  9.10. These modifs were copied from a recent commit in _ros_bridge/master_, so I didn't commit them here.
- It doesn't work with the launch file _carla_ad_demo/carla_ad_demo_with_scenario.launch.py_ yet, as this requires rviz

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/386)

### CODE REVIEW

**Comment by fpasch** [comment]
closes #280

**Review by fpasch — CHANGES_REQUESTED** [review]
> Reviewed 12 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/386)* status: 12 of 15 files reviewed, 2 unresolved discussions (waiting on @fpasch and @jbmag)

___
*[carla_ros_scenario_runner/launch/carla_ros_scenario_runner.launch.py, line 34 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/386#-MJa-9B93b1SqoxtJ2jQ:-MJa-9B93b1SqoxtJ2jR:b-f9vww8) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/ce83209bdc3179b0eb5d7c647f754c53589b9b83/carla_ros_scenario_runner/launch/carla_ros_scenario_runner.launch.py#L34)):*
> ```Python
>             name='carla_ros_scenario_runner',
>             output='screen',
>             emulate_tty='True',
> ```

is this required, or a leftover from testing?
___
*[carla_ros_scenario_runner/src/carla_ros_scenario_runner/application_runner.py, line 104 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/386#-MJa1iz32HufAn6MAnI2:-MJa1iz49r-8uwWFbsmm:b-2worlr) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/ce83209bdc3179b0eb5d7c647f754c53589b9b83/carla_ros_scenario_runner/src/carla_ros_scenario_runner/application_runner.py#L104)):*
> ```
>         # if not os.path.isfile(executable):
>         #     raise KeyError("The executable {} does not exist".format(executable))
> ```
what's the issue with that?

**Review by jbmag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/386)* status: 12 of 15 files reviewed, 2 unresolved discussions (waiting on @fpasch)

___
*[carla_ros_scenario_runner/launch/carla_ros_scenario_runner.launch.py, line 34 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/386#-MJa-9B93b1SqoxtJ2jQ:-MJa2MD8CmdWvhAJquLD:bob2dw0) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/ce83209bdc3179b0eb5d7c647f754c53589b9b83/carla_ros_scenario_runner/launch/carla_ros_scenario_runner.launch.py#L34)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

is this required, or a leftover from testing?
</blockquote></details>

If we don't add this, only the logs of level 'warn' or higher appear in the console when using launch, it seems to be a common problem from what I've seen, at least in eloquent, so I'd say it's useful to keep....
___
*[carla_ros_scenario_runner/src/carla_ros_scenario_runner/application_runner.py, line 104 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/386#-MJa1iz32HufAn6MAnI2:-MJa35E-Clq-m9koAlQb:b-r2if42) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/ce83209bdc3179b0eb5d7c647f754c53589b9b83/carla_ros_scenario_runner/src/carla_ros_scenario_runner/application_runner.py#L104)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

> ```
>         # if not os.path.isfile(executable):
>         #     raise KeyError("The executable {} does not exist".format(executable))
> ```
what's the issue with that?
</blockquote></details>

to check if the command can be executed, it checks if it's a file, so as I wanted to use it with 'ros2 launch' it was raising an error.... it's true that there might be a more elegant way to avoid it than commenting it though...

**Review by fpasch — CHANGES_REQUESTED** [review]
> Reviewed 3 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/386)* status: all files reviewed, 1 unresolved discussion (waiting on @jbmag)

___
*[carla_ros_scenario_runner/src/carla_ros_scenario_runner/application_runner.py, line 104 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/386#-MJa1iz32HufAn6MAnI2:-MJa4LGfCU_a141GUPtJ:b-muh86h) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/ce83209bdc3179b0eb5d7c647f754c53589b9b83/carla_ros_scenario_runner/src/carla_ros_scenario_runner/application_runner.py#L104)):*
<details><summary><i>Previously, jbmag wrote…</i></summary><blockquote>

to check if the command can be executed, it checks if it's a file, so as I wanted to use it with 'ros2 launch' it was raising an error.... it's true that there might be a more elegant way to avoid it than commenting it though...
</blockquote></details>

alright. Then please just remove the commented code.

**Review by fpasch — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/386)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
