### PR TITLE
Added Lidar Sensor in carla_ad_demo

### PR DESCRIPTION
**Pull request by vedthakur5**
I realized that many people (including me) needed lidar sensor in carla_ad_demo. Therefore i have added the lidar sensor in sensors.json file in carla_ad_demo config with some id. Also i have added the lidar visualization in carla_ad_demo.rviz file with the appropriate topic and using the same id as in sensors.json file in carla_ad_demo

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/385)

### CODE REVIEW

**Review by fpasch — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/385)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @vedthakur5)

___
*[carla_ad_demo/config/sensors.json, line 59 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/385#-MJf1r6Q0Kfs_X1AK9rS:-MJf1r6Q0Kfs_X1AK9rT:b-1nb1jf) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/23b2b7dbb032466b57c0ff233024e06d058fc872/carla_ad_demo/config/sensors.json#L59)):*
> ```JSON
>             "lower_fov": -26.8,
>             "rotation_frequency": 20,
>             "sensor_tick": 0.0
> ```

please change sensor_tick to 0.05

**Comment by vedthakur5** [comment]
Ya I'll do it asap

**Comment by vedthakur5** [comment]
Ya I'll do it asap

**Review by fpasch — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/385)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
