### PR TITLE
Update radar node to publish pc2

### PR DESCRIPTION
**Pull request by Roosstef**
Add Pointcloud2 publisher to radar.py.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/379)

### CODE REVIEW

**Review by fpasch — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/379)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Roosstef)

___
*[carla_ros_bridge/src/carla_ros_bridge/radar.py, line 78 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/379#-MIOYnN04X46k66sQK65:-MIOAokj6nhbkFxu8qv7:b-ii273r) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/e5230df630b682cbc9a6e01ba00ae0c5040d269b/carla_ros_bridge/src/carla_ros_bridge/radar.py#L78)):*
> ```Python
> 
>         self.publish_message(self.get_topic_prefix() + "/radar", radar_msg)
>         self.publish_message(self.get_topic_prefix() + "/radar/PointCloud2", radar_msg_pc)
> ```

This would result e.g. in /ego_vehicle/radar/sensor01/radar/PointCloud2. Please replace by "/radar_points"

**Review by Roosstef — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/379)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @fpasch)

___
*[carla_ros_bridge/src/carla_ros_bridge/radar.py, line 78 at r1](https://reviewable.io/reviews/carla-simulator/ros-bridge/379#-MIOYnN04X46k66sQK65:-MIPAleY7LCHn71f3jj-:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/e5230df630b682cbc9a6e01ba00ae0c5040d269b/carla_ros_bridge/src/carla_ros_bridge/radar.py#L78)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

This would result e.g. in /ego_vehicle/radar/sensor01/radar/PointCloud2. Please replace by "/radar_points"
</blockquote></details>

Done.

**Review by Roosstef — COMMENTED** [review]
Changes done

**Comment by Roosstef** [comment]
Am I doing something wrong?
Do I have to carry out any actions to get this merged?

**Comment by joel-mb** [comment]
Hi @Roosstef
Sorry for our late reply. We recently updated the communication pipeline. Could you please adapt your PR to it? You just have to create the `PointCloud2` publisher in the sensor constructor and call it in the `sensor_data_updated` method instead of using the `publish_msg` method.
Take a look here: https://github.com/carla-simulator/ros-bridge/blob/master/carla_ros_bridge/src/carla_ros_bridge/radar.py
Thanks!

**Review by fpasch — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/379)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @fpasch and @Roosstef)

___
*[carla_ros_bridge/src/carla_ros_bridge/radar.py, line 55 at r4](https://reviewable.io/reviews/carla-simulator/ros-bridge/379#-MKeirsZ7Wa9HUWnSPJD:-MKeirsZ7Wa9HUWnSPJE:b-y0p8v2) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/52a84aa9f2a1ce8e46fc9f8ea3faca500d71dd2c/carla_ros_bridge/src/carla_ros_bridge/radar.py#L55)):*
> ```Python
>                                                queue_size=10)
> 
>         self.radar_pc_publisher = rospy.Publisher(self.get_topic_prefix() +
> ```

could you please add this new topic to the README and also update the changelog?

**Review by Roosstef — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/379)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @fpasch)

___
*[carla_ros_bridge/src/carla_ros_bridge/radar.py, line 55 at r4](https://reviewable.io/reviews/carla-simulator/ros-bridge/379#-MKeirsZ7Wa9HUWnSPJD:-MKenBgwBO0HUJZY-wDA:b-896fix) ([raw file](https://github.com/carla-simulator/ros-bridge/blob/52a84aa9f2a1ce8e46fc9f8ea3faca500d71dd2c/carla_ros_bridge/src/carla_ros_bridge/radar.py#L55)):*
<details><summary><i>Previously, fpasch (fpasch) wrote…</i></summary><blockquote>

could you please add this new topic to the README and also update the changelog?
</blockquote></details>

Done.

**Review by Roosstef — COMMENTED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/379)* status: all files reviewed, 1 unresolved discussion (waiting on @fpasch)

**Comment by fpasch** [comment]
One last thing before I approve it, could you please update https://github.com/carla-simulator/ros-bridge/blob/master/carla_ros_bridge/test/ros_bridge_client.py#L195 . Sorry for not mentioning it before.

**Review by Roosstef — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/379)* status: all files reviewed, 1 unresolved discussion (waiting on @fpasch)

**Review by fpasch — APPROVED** [review]
> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/ros-bridge/379)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
